spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ## kafka Properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.binitshrestha.order_service.event.OrderPlacedEvent
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ health, info, metrics ]
  endpoint:
    health:
      show-details: always

#Resilience properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

  #Resilience4J Timeout Property
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s

  #Resilience4J Retry properties
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s






logging:
  level:
    org:
      springframework:
        security: TRACE



#  management.health.fcircuitbreakers.enabled=true
#  management.endpoints.web.exposure.include=*
#  management.endpoint.health.show-details=always
#
#  #Resilinece4j Properties
#  resilience4j.circuitbreaker.instances.inventory.registerHealthIndicator=true
#  resilience4j.circuitbreaker.instances.inventory.event-consumer-buffer-size=10
#  resilience4j.circuitbreaker.instances.inventory.slidingWindowType=COUNT_BASED
#  resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=5
#  resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50
#  resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=5s
#  resilience4j.circuitbreaker.instances.inventory.permittedNumberOfCallsInHalfOpenState=3
#  resilience4j.circuitbreaker.instances.inventory.automaticTransitionFromOpenToHalfOpenEnabled=true
#
#  #Resilience4J Timeout Properties
#  resilience4j.timelimiter.instances.inventory.timeout-duration=3s
#
#  #Resilience4J Retry Properties
#  resilience4j.retry.instances.inventory.max-attempts=3